config/routes.rb
Step::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :posts
  root to: "user#index"
  match '/reg' => 'user#create' , via: [:get, :post]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name,:email, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
  def create
    @user = User.new(user_params)
    @user.save
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name,:password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Step</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user/index.html.erb
<html>
<%= form_for(:user, :url => reg_path , method: "post") do |f| %>
    <p> Your Name:  <%= f.text_field :name, :class=> "name" %></p>
    <p>  Password:  <%= f.text_field :password %></p>
    <p>  Email:     <%= f.email_field :email %></p>
    <p><%= submit_tag "Create Account" %></p>
<% end %>
</html>